name: "Roo AI Cleaning Assistant"
version: "0.1.0"
slug: "aicleaner"
description: "AI-powered room cleanliness analysis and to-do list generator."
url: "https://github.com/sporebattyl/hass-addon-aicleaner"
arch:
  - aarch64
  - amd64
  - armv7
startup: "application"
boot: "auto"
init: false
homeassistant_api: true
options:
  camera_entity: null
  gemini_api_key: null
  todo_list_entity: null
  update_frequency: 24
schema:
  camera_entity: str
  gemini_api_key: secret
  todo_list_entity: str
  update_frequency: int(1, 168)