name: "AICleaner v2.0"
version: "2.0.0"
slug: "aicleaner"
description: "Intelligent, multi-zone cleanliness management with comprehensive Lovelace UI."
url: "https://github.com/sporebattyl/Aiclean"
arch:
  - aarch64
  - amd64
  - armv7
startup: "application"
boot: "auto"
init: false
homeassistant_api: true
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Static file server for Lovelace cards"
map:
  - "config:ro"
  - "share:rw"
  - "ssl:ro"
  - "media:rw"
  - "addons:rw"
  - "backup:ro"

options:
  gemini_api_key: null
  display_name: "User"
  zones: []
schema:
  gemini_api_key: password
  display_name: str
  zones:
    - name: str
      icon: str
      purpose: str
      camera_entity: str
      todo_list_entity: str
      update_frequency: int(1,168)
      notifications_enabled: bool
      notification_service: str?
      notification_personality: list(default|roaster|comedian|jarvis|sargent|snarky)
      notify_on_create: bool
      notify_on_complete: bool