name: "Roo AI Cleaning Assistant"
version: "2.0.0"
slug: "aicleaner"
description: "AI-powered multi-zone home management assistant with advanced analytics"
url: "https://github.com/sporebattyl/Aiclean"
arch:
  - aarch64
  - amd64
  - armv7
startup: "application"
boot: "auto"
init: false
homeassistant_api: true
ingress: true
panel_icon: "mdi:robot-vacuum"
panel_title: "Roo Assistant"
ports:
  8099/tcp: 8099
schema:
  gemini_api_key: password
  default_personality: list(concise|snarky|encouraging)?
  global_notifications: bool?
  database_path: str?
  log_level: list(DEBUG|INFO|WARNING|ERROR)?
options:
  default_personality: "concise"
  global_notifications: true
  database_path: "/data/roo.db"
  log_level: "INFO"